services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network

  auth_service:
    build: ./backend/auth_service
    ports:
      - "8090:8090"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=super_secret_key
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
